// Description is at the end of the file
#pragma once

#ifndef DEVICE_DEFINITIONS_H_
#define DEVICE_DEFINITIONS_H_


/**************************************************************************************************/
/*                                                                                                */
/*                                      debug_pif definitions                                     */
/*                                                                                                */
/**************************************************************************************************/

#define DEBUG_ERROR_LOG_DEPTH                       (64U)
#define DEBUG_ERROR_LOG_VERSION                     (1U)

#ifndef DEBUG_BUFFER_SIZE
    #define DEBUG_BUFFER_SIZE                       (400U)
#endif

/**************************************************************************************************/
/*                                                                                                */
/*                                    clocking_pif definitions                                    */
/*                                                                                                */
/**************************************************************************************************/

#define ENABLE_PIF_CLOCKING_DEFINITIONS

#define HSE_CLOCK_FREQUENCY_HZ					(8000000U) //! Must contain frequency of external resonator
#define SYSTEM_CLOCK_SOURCE						PLL_HSE //! Possible options: HSI, HSE, PLL_HSI, PLL_HSE
#define SYSTEM_CLOCK_FREQUENCY_HZ				(72000000U) //! System clock frequency in Hz we want to achieve after clock setup

#define SYSTICK_INTERRUPT_FREQUENCY_HZ			10 //! Frequency of SysTick_Handler() interrupt call

/**************************************************************************************************/
/*                                                                                                */
/*                                   device_debug_pif definitions                                 */
/*                                                                                                */
/**************************************************************************************************/

#define DEBUG_UART_BUFFER_SIZE                  (256U)


/**************************************************************************************************/
/*                                                                                                */
/*                                   TMC2209_tb_pif definitions                                   */
/*                                                                                                */
/**************************************************************************************************/


///////////////////////////////////////////////////////////////

// @todo Everything below must be completely rewritten


// @ todo Add ADC clock definition that will define the clock speed we want for ADC and will update ADCx_CCR register accordingly and will
//			call error if it if impossible to get the exact needed ADC frequency. May be a bit of a hastle, therefoer task for later. Also important to make sure, that ADC clock will not be higher than 60Mhz
// @ note I think this definition should be moved to the ADC specific section according to new architecture


/**************************************************************************************************/
/*                                                                                                */
/*                              Error code blocks re-initialization                               */
/*                                                                                                */
/**************************************************************************************************/

#define CLOCK_ERRORS_OFFSET				(20U)

#endif /* PIF_DEFINITIONS_EXAMPLE_H_ */

/*!
 * 	This is the base file for Hople way of creating peripheral interfaces using our own HAL. In theory this file isn't needed when STM32 HAL or any similar HAL is used directly.
 * 	This is an example file that contains all peripherals for this particular test project. Ideally, in the future this file will be automatically generated by a tool, but at the moment it has to be recreated for every project.
 *
 *  This file contain all definitions that are used by all other _pif files for set up.
 *
 *  @ todo
 */
